In [3]:
import requests
import json
import pandas as pd
import datetime as dt

In [4]:
url = 'https://api.binance.us/api/v3/klines'
symbol = 'BTCBUSD'
interval = '1h'
start = str(int(dt.datetime(2021,1,1).timestamp()*1000))
end = str(int(dt.datetime(2021,12,1).timestamp()*1000))

In [5]:
params = {'symbol': symbol, 
          'interval': interval, 
          'startTime': start, 
          'endTime': end}

In [12]:
response_text = requests.get(url, params= params).text

In [13]:
# Отправка запроса API с помощью метода requests.get
response = requests.get(url, params=params)

# Проверка кода состояния ответа для подтверждения успешности запроса API
if response.status_code == 200:
    print("Успешный запрос API!")
else:
    print("Запрос API отклонен с кодом состояния:", response.status_code)

print(response_text)

Запрос API отклонен с кодом состояния: 403
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: IANsY5xv4Gl_eLpoHO-Cb9EcCmb334obEPC0PfWcFh2s4Xfa4Ry8ZQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

In [14]:
json_res = json.loads(response)

TypeError: the JSON object must be str, bytes or bytearray, not Response

In [15]:
json_res

NameError: name 'json_res' is not defined

In [12]:
df = pd.DataFrame(json_res)

df.columns = ['datetime', 'open', 'high', 'low', 'close', 'volume','close_time', 'qav', 'num_trades','taker_base_vol', 'taker_quote_vol', 'ignore']

In [13]:
df.head()

,datetime,open,high,low,close,volume,close_time,qav,num_trades,taker_base_vol,taker_quote_vol,ignore
0,1609459200000,28966.70000000,29084.03000000,28766.37000000,29034.25000000,3.58281500,1609462799999,103881.14776873,120,2.75314300,79871.70340003,0
1,1609462800000,29035.97000000,29521.33000000,29035.97000000,29443.25000000,7.58306600,1609466399999,222440.57206249,190,4.27068500,125141.85841164,0
2,1609466400000,29467.47000000,29518.54000000,29196.49000000,29256.76000000,1.65098500,1609469999999,48415.13348742,130,0.84758500,24861.76117622,0
3,1609470000000,29258.32000000,29408.95000000,29195.48000000,29354.01000000,1.43583200,1609473599999,42125.58500593,84,1.01987800,29926.40797902,0
4,1609473600000,29327.66000000,29439.64000000,29138.05000000,29262.43000000,2.48715600,1609477199999,72861.90054167,108,0.57099400,16755.01535307,0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   datetime         500 non-null    int64
 1   open             500 non-null    object
 2   high             500 non-null    object
 3   low              500 non-null    object
 4   close            500 non-null    object
 5   volume           500 non-null    object
 6   close_time       500 non-null    int64
 7   qav              500 non-null    object
 8   num_trades       500 non-null    int64
 9   taker_base_vol   500 non-null    object
 10  taker_quote_vol  500 non-null    object
 11  ignore           500 non-null    object
dtypes: int64(3), object(9)
memory usage: 47.0+ KB

In [15]:
df.index = [dt.datetime.fromtimestamp(x/1000.0) for x in df.datetime]

In [16]:
df.head()

,datetime,open,high,low,close,volume,close_time,qav,num_trades,taker_base_vol,taker_quote_vol,ignore
2021-01-01 00:00:00,1609459200000,28966.70000000,29084.03000000,28766.37000000,29034.25000000,3.58281500,1609462799999,103881.14776873,120,2.75314300,79871.70340003,0
2021-01-01 01:00:00,1609462800000,29035.97000000,29521.33000000,29035.97000000,29443.25000000,7.58306600,1609466399999,222440.57206249,190,4.27068500,125141.85841164,0
2021-01-01 02:00:00,1609466400000,29467.47000000,29518.54000000,29196.49000000,29256.76000000,1.65098500,1609469999999,48415.13348742,130,0.84758500,24861.76117622,0
2021-01-01 03:00:00,1609470000000,29258.32000000,29408.95000000,29195.48000000,29354.01000000,1.43583200,1609473599999,42125.58500593,84,1.01987800,29926.40797902,0
2021-01-01 04:00:00,1609473600000,29327.66000000,29439.64000000,29138.05000000,29262.43000000,2.48715600,1609477199999,72861.90054167,108,0.57099400,16755.01535307,0